import { Scenario, Building3D, SectorDefinition } from '../types/slam';

export const SCENARIOS: Record<string, Scenario> = {
  urban_disaster: {
    id: 'urban_disaster',
    name: 'Urban Disaster Mapping',
    description: 'Post-earthquake multi-block urban collapse reconnaissance. Autonomous 3-sector 3D visual reconstruction for rescue pathfinding.',
    threatLevel: 'TACTICAL_ADVISORY',
    initialZoom: 45,
    groundRadius: 180,
    sectors: [
      {
        id: 'Alpha',
        name: 'Sector Alpha (Commercial Core)',
        description: 'Multi-story collapsed structures and narrow corridors',
        center: { x: -65, y: 55, z: 0 },
        radius: 48,
        assignedAgent: 'AAV-01',
        buildingCount: 14,
      },
      {
        id: 'Bravo',
        name: 'Sector Bravo (Logistics Hub)',
        description: 'Warehouses, loading bays and fractured overpasses',
        center: { x: 70, y: 45, z: 0 },
        radius: 52,
        assignedAgent: 'AAV-02',
        buildingCount: 12,
      },
      {
        id: 'Charlie',
        name: 'Sector Charlie (Forward Perimeter)',
        description: 'Perimeter access road, substation and communications node',
        center: { x: 0, y: -75, z: 0 },
        radius: 50,
        assignedAgent: 'AAV-03',
        buildingCount: 10,
      },
    ],
    buildings: [
      // Sector Alpha (x: -95 to -35, y: 25 to 85)
      { id: 'b_a1', x: -60, y: 50, width: 22, depth: 18, height: 38, type: 'structure', sector: 'Alpha' },
      { id: 'b_a2', x: -82, y: 65, width: 16, depth: 16, height: 26, type: 'rubble', sector: 'Alpha' },
      { id: 'b_a3', x: -45, y: 70, width: 14, depth: 20, height: 44, type: 'structure', sector: 'Alpha' },
      { id: 'b_a4', x: -75, y: 35, width: 18, depth: 14, height: 18, type: 'rubble', sector: 'Alpha' },
      { id: 'b_a5', x: -50, y: 30, width: 12, depth: 12, height: 22, type: 'structure', sector: 'Alpha' },
      { id: 'b_a6', x: -90, y: 45, width: 15, depth: 15, height: 32, type: 'structure', sector: 'Alpha' },

      // Sector Bravo (x: 40 to 100, y: 20 to 75)
      { id: 'b_b1', x: 65, y: 40, width: 28, depth: 22, height: 18, type: 'industrial', sector: 'Bravo' },
      { id: 'b_b2', x: 85, y: 60, width: 20, depth: 16, height: 28, type: 'industrial', sector: 'Bravo' },
      { id: 'b_b3', x: 50, y: 65, width: 18, depth: 24, height: 34, type: 'structure', sector: 'Bravo' },
      { id: 'b_b4', x: 80, y: 25, width: 14, depth: 14, height: 15, type: 'rubble', sector: 'Bravo' },
      { id: 'b_b5', x: 55, y: 20, width: 16, depth: 20, height: 24, type: 'structure', sector: 'Bravo' },

      // Sector Charlie (x: -35 to 35, y: -95 to -50)
      { id: 'b_c1', x: 0, y: -75, width: 24, depth: 20, height: 20, type: 'industrial', sector: 'Charlie' },
      { id: 'b_c2', x: -25, y: -65, width: 16, depth: 16, height: 30, type: 'structure', sector: 'Charlie' },
      { id: 'b_c3', x: 25, y: -70, width: 18, depth: 18, height: 25, type: 'structure', sector: 'Charlie' },
      { id: 'b_c4', x: -20, y: -90, width: 22, depth: 14, height: 16, type: 'rubble', sector: 'Charlie' },
      { id: 'b_c5', x: 22, y: -88, width: 15, depth: 15, height: 22, type: 'structure', sector: 'Charlie' },

      // Central Base Station / Command MEC Node
      { id: 'b_mec', x: 0, y: 5, width: 14, depth: 14, height: 50, type: 'tower', sector: 'Neutral' },
      // Overlap zones (where shared visual landmarks occur!)
      { id: 'b_overlap_ab', x: 5, y: 55, width: 16, depth: 14, height: 36, type: 'structure', sector: 'Neutral' },
      { id: 'b_overlap_bc', x: 35, y: -15, width: 14, depth: 14, height: 28, type: 'structure', sector: 'Neutral' },
      { id: 'b_overlap_ca', x: -35, y: -15, width: 14, depth: 14, height: 30, type: 'structure', sector: 'Neutral' },
    ],
  },

  search_rescue: {
    id: 'search_rescue',
    name: 'Search & Rescue (Wildland/Camp)',
    description: 'Mountain valley search & rescue. Triangulating missing reconnaissance team across rugged terrain with sparse visual features.',
    threatLevel: 'DEFCON 4',
    initialZoom: 50,
    groundRadius: 200,
    sectors: [
      {
        id: 'Alpha',
        name: 'Sector Alpha (Ridge Outpost)',
        description: 'Steep ridge with watchtower and transmission antennas',
        center: { x: -70, y: 50, z: 0 },
        radius: 45,
        assignedAgent: 'AAV-01',
        buildingCount: 6,
      },
      {
        id: 'Bravo',
        name: 'Sector Bravo (Canyon Gorge)',
        description: 'Dry riverbed with dense boulder fields and abandoned huts',
        center: { x: 65, y: 55, z: 0 },
        radius: 48,
        assignedAgent: 'AAV-02',
        buildingCount: 7,
      },
      {
        id: 'Charlie',
        name: 'Sector Charlie (Valley Compound)',
        description: 'Remote supply buildings, bridge crossing, and helipad area',
        center: { x: 5, y: -70, z: 0 },
        radius: 50,
        assignedAgent: 'AAV-03',
        buildingCount: 8,
      },
    ],
    buildings: [
      { id: 'sr_1', x: -65, y: 48, width: 14, depth: 14, height: 24, type: 'structure', sector: 'Alpha' },
      { id: 'sr_2', x: -78, y: 60, width: 10, depth: 10, height: 32, type: 'tower', sector: 'Alpha' },
      { id: 'sr_3', x: 60, y: 50, width: 20, depth: 18, height: 16, type: 'rubble', sector: 'Bravo' },
      { id: 'sr_4', x: 75, y: 65, width: 16, depth: 14, height: 22, type: 'structure', sector: 'Bravo' },
      { id: 'sr_5', x: 0, y: -68, width: 25, depth: 22, height: 18, type: 'industrial', sector: 'Charlie' },
      { id: 'sr_6', x: 18, y: -75, width: 12, depth: 12, height: 20, type: 'structure', sector: 'Charlie' },
      { id: 'sr_mec', x: 0, y: 5, width: 12, depth: 12, height: 48, type: 'tower', sector: 'Neutral' },
      { id: 'sr_ab', x: 2, y: 50, width: 15, depth: 15, height: 26, type: 'structure', sector: 'Neutral' },
      { id: 'sr_bc', x: 30, y: -10, width: 12, depth: 12, height: 20, type: 'structure', sector: 'Neutral' },
      { id: 'sr_ca', x: -30, y: -10, width: 12, depth: 12, height: 22, type: 'structure', sector: 'Neutral' },
    ],
  },

  infrastructure_inspection: {
    id: 'infrastructure_inspection',
    name: 'Critical Infrastructure Surveillance',
    description: 'High-security perimeter monitoring of power grid substation, oil depot, and communications relay under 5G edge coordination.',
    threatLevel: 'DEFCON 3',
    initialZoom: 45,
    groundRadius: 180,
    sectors: [
      {
        id: 'Alpha',
        name: 'Sector Alpha (Substation)',
        description: 'High voltage transformers and switchyard gantry towers',
        center: { x: -60, y: 60, z: 0 },
        radius: 46,
        assignedAgent: 'AAV-01',
        buildingCount: 8,
      },
      {
        id: 'Bravo',
        name: 'Sector Bravo (Storage Silos)',
        description: 'Pressurized tank farms and pipeline distribution hubs',
        center: { x: 65, y: 45, z: 0 },
        radius: 50,
        assignedAgent: 'AAV-02',
        buildingCount: 9,
      },
      {
        id: 'Charlie',
        name: 'Sector Charlie (Control & Defense)',
        description: 'Command bunker, perimeter checkpoints and radar arrays',
        center: { x: -5, y: -72, z: 0 },
        radius: 48,
        assignedAgent: 'AAV-03',
        buildingCount: 7,
      },
    ],
    buildings: [
      { id: 'ii_1', x: -58, y: 55, width: 22, depth: 16, height: 22, type: 'industrial', sector: 'Alpha' },
      { id: 'ii_2', x: -70, y: 68, width: 12, depth: 12, height: 42, type: 'tower', sector: 'Alpha' },
      { id: 'ii_3', x: 60, y: 40, width: 26, depth: 26, height: 20, type: 'industrial', sector: 'Bravo' },
      { id: 'ii_4', x: 80, y: 55, width: 20, depth: 20, height: 25, type: 'industrial', sector: 'Bravo' },
      { id: 'ii_5', x: -5, y: -70, width: 28, depth: 20, height: 24, type: 'structure', sector: 'Charlie' },
      { id: 'ii_mec', x: 0, y: 5, width: 14, depth: 14, height: 52, type: 'tower', sector: 'Neutral' },
      { id: 'ii_ab', x: 4, y: 52, width: 16, depth: 14, height: 32, type: 'structure', sector: 'Neutral' },
      { id: 'ii_bc', x: 32, y: -12, width: 14, depth: 14, height: 26, type: 'structure', sector: 'Neutral' },
      { id: 'ii_ca', x: -32, y: -12, width: 14, depth: 14, height: 28, type: 'structure', sector: 'Neutral' },
    ],
  },
};
