import React from 'react';
import { SimulationState } from '../simulation/simulationEngine';
import { AAVTelemetry } from '../types/slam';
import { BarChart3, X, CheckCircle, ShieldAlert, Cpu, Wifi, Activity } from 'lucide-react';

interface AnalyticsModalProps {
  isOpen: boolean;
  onClose: () => void;
  simState: SimulationState;
}

export const AnalyticsModal: React.FC<AnalyticsModalProps> = ({
  isOpen,
  onClose,
  simState,
}) => {
  if (!isOpen) return null;

  const totalTimeSeconds = Math.round(simState.simTimeSeconds);
  const minutes = Math.floor(totalTimeSeconds / 60);
  const seconds = totalTimeSeconds % 60;

  const agentsList = Object.values(simState.agents) as AAVTelemetry[];

  // Aggregate metrics
  const totalKeyframes = agentsList.reduce((acc: number, a: AAVTelemetry) => acc + a.keyframesCount, 0);
  const totalLandmarks = agentsList.reduce((acc: number, a: AAVTelemetry) => acc + a.landmarksCount, 0);
  const totalDistanceMeters = agentsList.reduce(
    (acc: number, a: AAVTelemetry) => acc + a.trajectory.length * 1.8,
    0
  );
  const areaExploredSqM = Math.round(
    Math.min(95000, 15000 + (totalDistanceMeters * 35))
  );

  const mapCoveragePercent =
    simState.collabSlam.fusionStage === 'GLOBAL_FUSED'
      ? 100
      : Math.min(94, Math.round(20 + (totalKeyframes / 400) * 60));

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-sm p-4 font-sans antialiased select-none">
      <div className="bg-black border border-zinc-750 rounded-sm w-full max-w-4xl p-5 shadow-2xl flex flex-col gap-4 text-zinc-200 animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-zinc-800 pb-3 font-sans">
          <div className="flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-cyan-400" />
            <div>
              <h2 className="text-base font-semibold font-sans text-zinc-100">
                Mission Analytics & SLAM Benchmark Evaluation
              </h2>
              <p className="text-xs text-zinc-400 font-sans">
                Performance Telemetry: Multi-AAV Collaborative Visual SLAM over 5G MEC Architecture
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded hover:bg-zinc-900 text-zinc-400 hover:text-zinc-100 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Mandatory Research Notice / Simulation Disclaimer */}
        <div className="bg-amber-950/40 border border-amber-600/60 p-2.5 rounded-xs flex items-start gap-2.5 text-xs text-amber-200">
          <ShieldAlert className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
          <div>
            <span className="font-bold text-amber-300 mr-2">[SIMULATION NOTICE]:</span>
            All flight trajectories, ORB feature correspondences, 5G wireless metrics, and MEC solver compute loads are generated by a deterministic mathematical simulation testbed (based on COVINS / ORB-SLAM3 benchmarks). Metric values represent simulated edge validation conditions.
          </div>
        </div>

        {/* Analytics Grid: All 13 metrics requested in the prompt */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2.5 text-xs">
          {/* Total Mission Time */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Total Mission Time:</span>
            <span className="text-lg font-bold text-zinc-100">
              {minutes}m {seconds}s
            </span>
            <span className="text-[9px] text-zinc-500 block">SIMULATION</span>
          </div>

          {/* Distance Covered */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Distance Covered:</span>
            <span className="text-lg font-bold text-cyan-300">
              {(totalDistanceMeters / 1000).toFixed(2)} km
            </span>
            <span className="text-[9px] text-zinc-500 block">Cumulative 3 AAVs</span>
          </div>

          {/* Area Explored */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Area Explored:</span>
            <span className="text-lg font-bold text-emerald-400">
              {(areaExploredSqM / 10000).toFixed(1)} ha
            </span>
            <span className="text-[9px] text-zinc-500 block">{areaExploredSqM.toLocaleString()} m²</span>
          </div>

          {/* Global Map Coverage */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Global Map Coverage:</span>
            <span className="text-lg font-bold text-cyan-400">
              {mapCoveragePercent}%
            </span>
            <span className="text-[9px] text-zinc-500 block">Target Sector Grid</span>
          </div>

          {/* Map Fusion Time */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Map Fusion Time:</span>
            <span className="text-lg font-bold text-yellow-300">
              {simState.collabSlam.fusionStage === 'GLOBAL_FUSED' ? '4.82 s' : 'Pending'}
            </span>
            <span className="text-[9px] text-zinc-500 block">g2o LM Solver Convergence</span>
          </div>

          {/* Average Network Latency */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Average Latency:</span>
            <span className="text-lg font-bold text-zinc-100">
              {simState.network.latencyMs} ms
            </span>
            <span className="text-[9px] text-zinc-500 block">5G Radio Bearer</span>
          </div>

          {/* Average Throughput */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Average Throughput:</span>
            <span className="text-lg font-bold text-cyan-300">
              {simState.network.throughputMbps} Mbps
            </span>
            <span className="text-[9px] text-zinc-500 block">Aggregate Uplink</span>
          </div>

          {/* Packet Loss */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Packet Loss:</span>
            <span className="text-lg font-bold text-emerald-400">
              {simState.network.packetLossPercent}%
            </span>
            <span className="text-[9px] text-zinc-500 block">HARQ Layer</span>
          </div>

          {/* MEC CPU Usage */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">MEC CPU Usage:</span>
            <span className="text-lg font-bold text-zinc-200">
              {simState.mec.cpuUsage}%
            </span>
            <span className="text-[9px] text-zinc-500 block">64 Cores</span>
          </div>

          {/* MEC GPU Usage */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">MEC GPU Usage:</span>
            <span className="text-lg font-bold text-zinc-200">
              {simState.mec.gpuUsage}%
            </span>
            <span className="text-[9px] text-zinc-500 block">Tensor Acceleration</span>
          </div>

          {/* Number of Landmarks */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Number of Landmarks:</span>
            <span className="text-lg font-bold text-cyan-300">
              {totalLandmarks.toLocaleString()}
            </span>
            <span className="text-[9px] text-zinc-500 block">3D Triangulated Pts</span>
          </div>

          {/* Number of Keyframes */}
          <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800">
            <span className="text-[10px] text-zinc-400 block">Number of Keyframes:</span>
            <span className="text-lg font-bold text-zinc-100">
              {totalKeyframes.toLocaleString()}
            </span>
            <span className="text-[9px] text-zinc-500 block">Graph Vertices</span>
          </div>
        </div>

        {/* Multi-Agent Breakdown Table */}
        <div className="bg-zinc-950 p-3 rounded-xs border border-zinc-800 text-xs">
          <span className="text-zinc-400 text-[10px] font-bold block mb-2">
            AGENT INDIVIDUAL PERFORMANCE BREAKDOWN:
          </span>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-[11px]">
              <thead className="text-zinc-500 border-b border-zinc-800">
                <tr>
                  <th className="py-1">CALLSIGN</th>
                  <th>SECTOR</th>
                  <th>KEYFRAMES</th>
                  <th>LANDMARKS</th>
                  <th>BATTERY</th>
                  <th>VIO DRIFT RMSE</th>
                  <th>5G UPLINK</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-900 text-zinc-300">
                {agentsList.map((a) => (
                  <tr key={a.id}>
                    <td className="py-1.5 font-bold" style={{ color: a.color }}>
                      {a.callsign}
                    </td>
                    <td>Sector {a.sector}</td>
                    <td>{a.keyframesCount.toLocaleString()}</td>
                    <td className="text-cyan-400">{a.landmarksCount.toLocaleString()}</td>
                    <td>{Math.round(a.battery)}%</td>
                    <td className="text-emerald-400">{a.visualOdometryDrift.toFixed(1)} cm</td>
                    <td>{a.uplinkRateMbps} Mbps</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-between items-center pt-2 border-t border-zinc-800">
          <span className="text-[11px] text-zinc-500">
            Data synchronized via central simulation telemetry bus.
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-xs rounded-xs cursor-pointer transition-colors"
          >
            CLOSE ANALYTICS
          </button>
        </div>
      </div>
    </div>
  );
};
